### ISSUE TITLE
JSON schema version is still 0.1

### ISSUE THREAD

**Issue by apetrynet** [ascmitc/fdl#2]
The provided JSON schema is set to version 0.1 while the spec has reached 1.0.
Validating files produced to spec 1.0 against the current schema fails as the versions don't align.

**Comment by hjmallon** [comment]
This is now being discussed, the PDF spec still says major: 0, minor: 1 so the schema matches that. I think it maybe should have been updated to major: 1, minor: 0, so we will see what comes out of this.

**Comment by jessekorosi** [comment]
This has been updated
