### ISSUE TITLE
Add JSONPath “address” information to the Class (and Attribute?) sections of the specification

### ISSUE THREAD

**Issue by davidbkhall** [ascmitc/fdl#6]
- Aligned on in 1/16/23 committee meeting
- Should be included in v1.1 Specification document

@hjmallon [in Slack](https://www.google.com/url?q=https://ascmitcwfmm.slack.com/archives/C0188N3P4QJ/p1705428114416509&sa=D&source=docs&ust=1705466681464662&usg=AOvVaw37_QlvGZBa1P18hJeHvuA4):
The `$.` paths seem like JSONPath, see https://jsonpath.com/
Example for showing where canvases is would be `$.contexts[0].canvases` (paste an fdl into the left pane to try that yourself)

**Comment by jessekorosi** [comment]
This has been addressed in version 1.1 to our specification
